name: Multi_label_Pycharm
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - et_xmlfile=1.1.0
  - icc_rt=2019.0.0
  - intel-openmp=2021.2.0
  - jdcal=1.4.1
  - joblib=1.0.1
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - numpy=1.20.2
  - numpy-base=1.20.2
  - openpyxl=3.0.7
  - openssl=1.1.1k
  - pandas=1.2.4
  - pip=21.0.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - pytz=2021.1
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - threadpoolctl=2.1.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - xlrd=2.0.1
  - pip:
    - neattext=
